// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/mail.proto

package service

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for MailService service

func NewMailServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for MailService service

type MailService interface {
	Call(ctx context.Context, in *MailCallRequest, opts ...client.CallOption) (*MailCallResponse, error)
}

type mailService struct {
	c    client.Client
	name string
}

func NewMailService(name string, c client.Client) MailService {
	return &mailService{
		c:    c,
		name: name,
	}
}

func (c *mailService) Call(ctx context.Context, in *MailCallRequest, opts ...client.CallOption) (*MailCallResponse, error) {
	req := c.c.NewRequest(c.name, "MailService.Call", in)
	out := new(MailCallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MailService service

type MailServiceHandler interface {
	Call(context.Context, *MailCallRequest, *MailCallResponse) error
}

func RegisterMailServiceHandler(s server.Server, hdlr MailServiceHandler, opts ...server.HandlerOption) error {
	type mailService interface {
		Call(ctx context.Context, in *MailCallRequest, out *MailCallResponse) error
	}
	type MailService struct {
		mailService
	}
	h := &mailServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&MailService{h}, opts...))
}

type mailServiceHandler struct {
	MailServiceHandler
}

func (h *mailServiceHandler) Call(ctx context.Context, in *MailCallRequest, out *MailCallResponse) error {
	return h.MailServiceHandler.Call(ctx, in, out)
}
