// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/service.proto

package service

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Service service

func NewServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Service service

type Service interface {
	Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error)
	ClientStream(ctx context.Context, opts ...client.CallOption) (Service_ClientStreamService, error)
	ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Service_ServerStreamService, error)
	BidiStream(ctx context.Context, opts ...client.CallOption) (Service_BidiStreamService, error)
}

type service struct {
	c    client.Client
	name string
}

func NewService(name string, c client.Client) Service {
	return &service{
		c:    c,
		name: name,
	}
}

func (c *service) Call(ctx context.Context, in *CallRequest, opts ...client.CallOption) (*CallResponse, error) {
	req := c.c.NewRequest(c.name, "Service.Call", in)
	out := new(CallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *service) ClientStream(ctx context.Context, opts ...client.CallOption) (Service_ClientStreamService, error) {
	req := c.c.NewRequest(c.name, "Service.ClientStream", &ClientStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &serviceClientStream{stream}, nil
}

type Service_ClientStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ClientStreamRequest) error
}

type serviceClientStream struct {
	stream client.Stream
}

func (x *serviceClientStream) Close() error {
	return x.stream.Close()
}

func (x *serviceClientStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serviceClientStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serviceClientStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serviceClientStream) Send(m *ClientStreamRequest) error {
	return x.stream.Send(m)
}

func (c *service) ServerStream(ctx context.Context, in *ServerStreamRequest, opts ...client.CallOption) (Service_ServerStreamService, error) {
	req := c.c.NewRequest(c.name, "Service.ServerStream", &ServerStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &serviceServerStream{stream}, nil
}

type Service_ServerStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ServerStreamResponse, error)
}

type serviceServerStream struct {
	stream client.Stream
}

func (x *serviceServerStream) Close() error {
	return x.stream.Close()
}

func (x *serviceServerStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serviceServerStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serviceServerStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serviceServerStream) Recv() (*ServerStreamResponse, error) {
	m := new(ServerStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *service) BidiStream(ctx context.Context, opts ...client.CallOption) (Service_BidiStreamService, error) {
	req := c.c.NewRequest(c.name, "Service.BidiStream", &BidiStreamRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &serviceBidiStream{stream}, nil
}

type Service_BidiStreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamRequest) error
	Recv() (*BidiStreamResponse, error)
}

type serviceBidiStream struct {
	stream client.Stream
}

func (x *serviceBidiStream) Close() error {
	return x.stream.Close()
}

func (x *serviceBidiStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serviceBidiStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serviceBidiStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serviceBidiStream) Send(m *BidiStreamRequest) error {
	return x.stream.Send(m)
}

func (x *serviceBidiStream) Recv() (*BidiStreamResponse, error) {
	m := new(BidiStreamResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Service service

type ServiceHandler interface {
	Call(context.Context, *CallRequest, *CallResponse) error
	ClientStream(context.Context, Service_ClientStreamStream) error
	ServerStream(context.Context, *ServerStreamRequest, Service_ServerStreamStream) error
	BidiStream(context.Context, Service_BidiStreamStream) error
}

func RegisterServiceHandler(s server.Server, hdlr ServiceHandler, opts ...server.HandlerOption) error {
	type service interface {
		Call(ctx context.Context, in *CallRequest, out *CallResponse) error
		ClientStream(ctx context.Context, stream server.Stream) error
		ServerStream(ctx context.Context, stream server.Stream) error
		BidiStream(ctx context.Context, stream server.Stream) error
	}
	type Service struct {
		service
	}
	h := &serviceHandler{hdlr}
	return s.Handle(s.NewHandler(&Service{h}, opts...))
}

type serviceHandler struct {
	ServiceHandler
}

func (h *serviceHandler) Call(ctx context.Context, in *CallRequest, out *CallResponse) error {
	return h.ServiceHandler.Call(ctx, in, out)
}

func (h *serviceHandler) ClientStream(ctx context.Context, stream server.Stream) error {
	return h.ServiceHandler.ClientStream(ctx, &serviceClientStreamStream{stream})
}

type Service_ClientStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*ClientStreamRequest, error)
}

type serviceClientStreamStream struct {
	stream server.Stream
}

func (x *serviceClientStreamStream) Close() error {
	return x.stream.Close()
}

func (x *serviceClientStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serviceClientStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serviceClientStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serviceClientStreamStream) Recv() (*ClientStreamRequest, error) {
	m := new(ClientStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (h *serviceHandler) ServerStream(ctx context.Context, stream server.Stream) error {
	m := new(ServerStreamRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.ServiceHandler.ServerStream(ctx, m, &serviceServerStreamStream{stream})
}

type Service_ServerStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*ServerStreamResponse) error
}

type serviceServerStreamStream struct {
	stream server.Stream
}

func (x *serviceServerStreamStream) Close() error {
	return x.stream.Close()
}

func (x *serviceServerStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serviceServerStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serviceServerStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serviceServerStreamStream) Send(m *ServerStreamResponse) error {
	return x.stream.Send(m)
}

func (h *serviceHandler) BidiStream(ctx context.Context, stream server.Stream) error {
	return h.ServiceHandler.BidiStream(ctx, &serviceBidiStreamStream{stream})
}

type Service_BidiStreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*BidiStreamResponse) error
	Recv() (*BidiStreamRequest, error)
}

type serviceBidiStreamStream struct {
	stream server.Stream
}

func (x *serviceBidiStreamStream) Close() error {
	return x.stream.Close()
}

func (x *serviceBidiStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *serviceBidiStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *serviceBidiStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *serviceBidiStreamStream) Send(m *BidiStreamResponse) error {
	return x.stream.Send(m)
}

func (x *serviceBidiStreamStream) Recv() (*BidiStreamRequest, error) {
	m := new(BidiStreamRequest)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
