// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/sms.proto

package service

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for SmsService service

func NewSmsServiceEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for SmsService service

type SmsService interface {
	Call(ctx context.Context, in *SmsCallRequest, opts ...client.CallOption) (*SmsCallResponse, error)
}

type smsService struct {
	c    client.Client
	name string
}

func NewSmsService(name string, c client.Client) SmsService {
	return &smsService{
		c:    c,
		name: name,
	}
}

func (c *smsService) Call(ctx context.Context, in *SmsCallRequest, opts ...client.CallOption) (*SmsCallResponse, error) {
	req := c.c.NewRequest(c.name, "SmsService.Call", in)
	out := new(SmsCallResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SmsService service

type SmsServiceHandler interface {
	Call(context.Context, *SmsCallRequest, *SmsCallResponse) error
}

func RegisterSmsServiceHandler(s server.Server, hdlr SmsServiceHandler, opts ...server.HandlerOption) error {
	type smsService interface {
		Call(ctx context.Context, in *SmsCallRequest, out *SmsCallResponse) error
	}
	type SmsService struct {
		smsService
	}
	h := &smsServiceHandler{hdlr}
	return s.Handle(s.NewHandler(&SmsService{h}, opts...))
}

type smsServiceHandler struct {
	SmsServiceHandler
}

func (h *smsServiceHandler) Call(ctx context.Context, in *SmsCallRequest, out *SmsCallResponse) error {
	return h.SmsServiceHandler.Call(ctx, in, out)
}
